<?php
return [
    'en' => 'English',
    'ar' => 'Arabic',
    'de' => 'German',
    'es' => 'Spanish',
    'et' => 'Estonian',
    'fa' => 'Persian',
    'fr' => 'French',
    'id' => 'Indonesian',
    'it' => 'Italian',
    'nl' => 'Dutch',
    'pl' => 'Polish',
    'pt' => 'Portuguese',
    'ro' => 'Romanian',
    'ru' => 'Russian',
    'th' => 'Thai',
    'tr' => 'Turkish',
    'pt-br' => 'Portuguese (Brazilian)',
    'zh-cn' => 'Chinese (Simplified)',
    'zh-tw' => 'Chinese (Traditional)',
];